const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94768211853"
const SESSION_ID = "PRABATH-MD~sN402KoZ#OPfyo0pSPdU5YOpyXqlM9KYnkRaYvedi6LfYkBNSrEI"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
